---
_extends: .github:common-settings.yaml

repository:
  name: sparkle
  description: ✨ TypeScript Playground ✨
  topics: typescript, playground, next-js, react, vite

branches:
  - name: main
    protection:
      enforce_admins: true
      required_linear_history: true
      required_pull_request_reviews: null
      required_status_checks:
        strict: false
        contexts: ['Build', 'Renovate / Renovate']
      restrictions: null
