config:
  extends: ./node_modules/markdownlint/style/cirosantilli.json
  line-length: false
  list-marker-space:
    ul_single: 1
    ol_single: 1
    ul_multi: 1
    ol_multi: 1

globs:
  - '**/*.md'
  - '!node_modules'
  - '!.cursorrules'
