bracketSpacing: false
printWidth: 120
semi: false
singleQuote: true
tabWidth: 2
overrides:
  - files:
      - '.vscode/*.json'
    options:
      tabWidth: 4
  - files:
      - '*.md'
    options:
      singleQuote: false
