packages:
  - packages/*
  - scripts

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver

overrides:
  jiti: <2.2.0

shamefullyHoist: true
