autoInstallPeers: true

dedupePeerDependents: true

engineStrict: true

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'

packages:
  - packages/*
  - apps/*
  - docs
  - scripts

onlyBuiltDependencies:
  - '@swc/core'
  - chromedriver
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver

overrides:
  tmp@<0.2.4: ^0.2.4

preferWorkspacePackages: true

resolutionMode: highest

savePrefix: ''

saveWorkspaceProtocol: rolling

shamefullyHoist: true

strictPeerDependencies: false
