packages:
  - packages/*
  - apps/*
  - docs
  - scripts

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'

onlyBuiltDependencies:
  - '@swc/core'
  - chromedriver
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver

overrides:
  jiti: <2.2.0

shamefullyHoist: true
