autoInstallPeers: true

dedupePeerDependents: true

engineStrict: true

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'

packages:
  - packages/*
  - apps/*
  - docs
  - scripts

allowBuilds:
  '@swc/core': true
  chromedriver: true
  esbuild: true
  sharp: true
  simple-git-hooks: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@swc/core'
  - chromedriver
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver

overrides:
  tmp@<0.2.6: ^0.2.6

preferWorkspacePackages: true

resolutionMode: highest

savePrefix: ''

saveWorkspaceProtocol: rolling

shamefullyHoist: true

strictPeerDependencies: false
