---
# Based on https://gist.github.com/belgattitude/838b2eba30c324f1f0033a797bab2e31
name: Setup CI
description: Setup pnpm, configure caches, and install dependencies

inputs:
  install-zig:
    description: 'Whether to install Zig (default: true)'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@61bc82c7df449f480d8aa43c14cfced3c0aec42b
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        cache: pnpm
        node-version-file: .node-version

    - name: Setup Zig
      if: ${{ inputs.install-zig == 'true' }}
      uses: mlugg/setup-zig@fa65c4058643678a4e4a9a60513944a7d8d35440 # v2.1.0

    - name: Restore development related caches
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        key: ${{ runner.os }}-development-cache-${{ hashFiles('**/pnpm-lock.yaml', '**/*.ts', 'turbo.json') }}
        path: |
          .cache
          **/.tsdown
          **/.turbo
          **/coverage
          **/tsconfig.tsbuildinfo
        restore-keys: ${{ runner.os }}-development-cache-

    - name: Bootstrap monorepo
      run: pnpm install
      shell: 'bash -Eeuo pipefail {0}'
