/**
 * Tests for scripts/bootstrap-graph/pr-normalize.ts's PR-body description
 * normalization: deterministic (no-model) selection of retained content,
 * a 2000-Unicode-codepoint description budget, and raw-vs-retained secret
 * scan comparison used to distinguish a hard-fail-worthy retained match
 * from a redacted-source-only warning.
 *
 * Fixtures below are SYNTHETIC, shape-equivalent stand-ins for three real
 * diagnosed false-positive cases (redacted findings report, not reproduced
 * here): a Renovate dependency-update PR whose collapsed release-notes
 * `<details>` block contains changelog prose describing credential
 * redaction (matches the `credentialed-url` rule), and a second whose
 * release notes describe a fenced registry-auth-token example. All
 * credential-shaped values below are dummy/synthetic, never real secrets.
 */
import {standardAfterEach, standardBeforeEach} from '@sparkle/test-utils/lifecycle'
import {afterEach, beforeEach, describe, expect, it} from 'vitest'

import {normalizePrBody} from './pr-normalize.js'

beforeEach(() => {
  standardBeforeEach()
})

afterEach(() => {
  standardAfterEach()
})

function basePr(body: string, overrides: {number?: number; title?: string} = {}) {
  return {
    number: overrides.number ?? 100,
    title: overrides.title ?? 'chore(deps): update dependency',
    body,
    files: ['pnpm-lock.yaml'],
    mergeCommitSha: 'sha100',
  }
}

const CLIP_NOTICE = ' [description truncated to fit budget]'

describe('normalizePrBody: ordinary PR summary (no boilerplate)', () => {
  it('retains an ordinary leading summary paragraph verbatim, trimmed', () => {
    const pr = basePr('This PR adds the bootstrap script.\n\nCloses #99.')
    const normalized = normalizePrBody(pr)
    expect(normalized.summary).toBe('This PR adds the bootstrap script.\n\nCloses #99.')
    expect(normalized.clipped).toBe(false)
    expect(normalized.usedTitleFallback).toBe(false)
  })

  it('preserves number, title, files, and merge commit sha unchanged', () => {
    const pr = basePr('b', {number: 42, title: 'fix: bug'})
    const normalized = normalizePrBody({...pr, files: ['a.ts', 'b.ts']})
    expect(normalized.number).toBe(42)
    expect(normalized.title).toBe('fix: bug')
    expect(normalized.files).toEqual(['a.ts', 'b.ts'])
    expect(normalized.mergeCommitSha).toBe('sha100')
  })

  it('defaults confidence to 75', () => {
    const normalized = normalizePrBody(basePr('b'))
    expect(normalized.confidence).toBe(75)
  })
})

describe('normalizePrBody: deterministic omission of boilerplate/release-notes/sponsors', () => {
  it('omits a collapsed <details> release-notes block, retaining the ordinary leading paragraph', () => {
    const body = [
      'This PR contains the following updates:',
      '',
      '| Package | Change |',
      '| --- | --- |',
      '| widget | 1.0.0 -> 1.1.0 |',
      '',
      '<details>',
      '<summary>widget (widget)</summary>',
      '',
      '### 1.1.0',
      '',
      'Some third-party release notes prose that should never end up in the retained description.',
      '',
      '</details>',
    ].join('\n')
    const normalized = normalizePrBody(basePr(body))
    expect(normalized.summary).toContain('This PR contains the following updates:')
    expect(normalized.summary).toContain('| widget | 1.0.0 -> 1.1.0 |')
    expect(normalized.summary).not.toContain('third-party release notes prose')
  })

  it('omits a sponsors block delimited by an HTML comment marker', () => {
    const body = [
      'This PR contains the following updates.',
      '',
      '<!-- sponsors -->',
      '#### Platinum Sponsors',
      '<table><tbody><tr><td>Acme Corp</td></tr></tbody></table>',
    ].join('\n')
    const normalized = normalizePrBody(basePr(body))
    expect(normalized.summary).toContain('This PR contains the following updates.')
    expect(normalized.summary).not.toContain('Platinum Sponsors')
    expect(normalized.summary).not.toContain('Acme Corp')
  })

  it('omits a badge/shield image line', () => {
    const body = [
      'Ordinary summary paragraph.',
      '',
      '[![some-badge](https://img.shields.io/badge/x-y-z)](https://example.com)',
    ].join('\n')
    const normalized = normalizePrBody(basePr(body))
    expect(normalized.summary).toContain('Ordinary summary paragraph.')
    expect(normalized.summary).not.toContain('img.shields.io')
  })

  it('omits the Renovate "Configuration" boilerplate footer and everything after it', () => {
    const body = [
      'Ordinary summary paragraph.',
      '',
      '### Configuration',
      '',
      'Schedule: every weekend.',
      '',
      'This PR was generated by Mend Renovate.',
    ].join('\n')
    const normalized = normalizePrBody(basePr(body))
    expect(normalized.summary).toContain('Ordinary summary paragraph.')
    expect(normalized.summary).not.toContain('Mend Renovate')
    expect(normalized.summary).not.toContain('Schedule: every weekend')
  })

  it('falls back to a bare "PR #N: title" label when nothing usable remains after omission — never inventing rationale', () => {
    const body = ['<details>', '<summary>x</summary>', 'release notes only', '</details>'].join('\n')
    const normalized = normalizePrBody(basePr(body, {number: 77, title: 'chore(deps): bump widget'}))
    expect(normalized.summary).toBe('PR #77: chore(deps): bump widget')
    expect(normalized.usedTitleFallback).toBe(true)
    expect(normalized.clipped).toBe(false)
  })
})

describe('normalizePrBody: nested/attributed <details> release-notes blocks (depth-aware, tag-position scanning)', () => {
  it('removes a single, non-nested <details>...</details> block (existing baseline behavior preserved)', () => {
    const body = 'INTRO\n\n<details><summary>x</summary>RELEASE NOTES</details>\n\nTRAILER'
    const normalized = normalizePrBody(basePr(body))
    expect(normalized.summary).toContain('INTRO')
    expect(normalized.summary).toContain('TRAILER')
    expect(normalized.summary).not.toContain('RELEASE NOTES')
  })

  it('removes a NESTED <details> block entirely as one balanced outermost range: INTRO <details>outer<details>inner</details>outer-tail</details> TRAILER -> INTRO TRAILER', () => {
    const body = 'INTRO\n\n<details>OUTER<details>INNER</details>OUTER_TAIL</details>\n\nTRAILER'
    const normalized = normalizePrBody(basePr(body))
    expect(normalized.summary).toContain('INTRO')
    expect(normalized.summary).toContain('TRAILER')
    expect(normalized.summary).not.toContain('OUTER')
    expect(normalized.summary).not.toContain('INNER')
    expect(normalized.summary).not.toContain('OUTER_TAIL')
  })

  it('handles an opening <details> tag with attributes (e.g. <details open> or <details data-x="1">) the same as a bare <details>', () => {
    const bodyOpenAttr = 'INTRO\n\n<details open>RELEASE NOTES</details>\n\nTRAILER'
    const normalizedOpenAttr = normalizePrBody(basePr(bodyOpenAttr))
    expect(normalizedOpenAttr.summary).toContain('INTRO')
    expect(normalizedOpenAttr.summary).toContain('TRAILER')
    expect(normalizedOpenAttr.summary).not.toContain('RELEASE NOTES')

    const bodyDataAttr = 'INTRO\n\n<details data-collapsed="true" id="x">RELEASE NOTES</details>\n\nTRAILER'
    const normalizedDataAttr = normalizePrBody(basePr(bodyDataAttr))
    expect(normalizedDataAttr.summary).toContain('INTRO')
    expect(normalizedDataAttr.summary).toContain('TRAILER')
    expect(normalizedDataAttr.summary).not.toContain('RELEASE NOTES')
  })

  it('removes two SIBLING <details> blocks independently, retaining the ordinary text between and around them', () => {
    const body = 'INTRO\n\n<details>FIRST</details>\n\nMIDDLE\n\n<details>SECOND</details>\n\nTRAILER'
    const normalized = normalizePrBody(basePr(body))
    expect(normalized.summary).toContain('INTRO')
    expect(normalized.summary).toContain('MIDDLE')
    expect(normalized.summary).toContain('TRAILER')
    expect(normalized.summary).not.toContain('FIRST')
    expect(normalized.summary).not.toContain('SECOND')
  })

  it('an unmatched/unclosed opening <details> tag with no closing tag at all is left in place deterministically, never swallowing unrelated preceding content or leaking a stray closing marker', () => {
    const body = 'INTRO\n\n<details>UNCLOSED CONTENT RUNS TO THE END'
    const normalized = normalizePrBody(basePr(body))
    // No balanced range exists to remove — the text is left exactly as selection found it (still
    // subject to the ordinary budget/other-category rules), never silently deleted wholesale nor
    // partially truncated at the unmatched tag.
    expect(normalized.summary).toContain('INTRO')
    expect(normalized.summary).toContain('UNCLOSED CONTENT RUNS TO THE END')
  })

  it('an unmatched/orphaned closing </details> tag with no preceding opening tag is left in place, never consuming unrelated preceding content', () => {
    const body = 'INTRO\n\nSTRAY CLOSING TAG FOLLOWS\n\n</details>\n\nTRAILER'
    const normalized = normalizePrBody(basePr(body))
    expect(normalized.summary).toContain('INTRO')
    expect(normalized.summary).toContain('STRAY CLOSING TAG FOLLOWS')
    expect(normalized.summary).toContain('TRAILER')
  })
})

describe('normalizePrBody: 2000-Unicode-codepoint description budget (scanner-independent boundary: paragraph -> line -> whitespace -> title fallback)', () => {
  it('does not clip content at or under the budget', () => {
    const body = 'x'.repeat(2000)
    const normalized = normalizePrBody(basePr(body))
    expect(normalized.clipped).toBe(false)
    expect([...normalized.summary]).toHaveLength(2000)
  })

  it('B1 SAFETY: an oversized single unbroken run with NO paragraph/line/whitespace boundary anywhere before the budget never hard-cuts mid-content — falls back to the title label instead of a partial cut', () => {
    const body = 'x'.repeat(5000)
    const normalized = normalizePrBody(basePr(body, {number: 55, title: 'chore: oversized unbroken body'}))
    expect(normalized.usedTitleFallback).toBe(true)
    expect(normalized.summary).toBe('PR #55: chore: oversized unbroken body')
    expect(normalized.clipped).toBe(false)
    expect(normalized.summary).not.toContain('x'.repeat(50))
  })

  it('a long paragraph WITH whitespace (ordinary prose, no newlines) clips at the last whitespace boundary at or before the budget — never mid-word', () => {
    const words = Array.from({length: 600}, (_, i) => `word${i}`)
    const body = words.join(' ')
    const normalized = normalizePrBody(basePr(body))
    expect(normalized.clipped).toBe(true)
    expect([...normalized.summary].length).toBeLessThanOrEqual(2000)
    expect(normalized.summary.endsWith(CLIP_NOTICE)).toBe(true)
    const withoutNotice = normalized.summary.slice(0, -CLIP_NOTICE.length)
    expect(body.startsWith(withoutNotice)).toBe(true)
    expect(withoutNotice.endsWith(' ')).toBe(false)
    const nextChar = body[withoutNotice.length]
    expect(nextChar === undefined || nextChar === ' ').toBe(true)
  })

  it('clips at the last paragraph/row boundary at or before the budget, never mid-line, and stays within budget', () => {
    const line = `| widget-${'a'.repeat(40)} | 1.0.0 -> 1.1.0 |`
    const body = Array.from({length: 100}, (_, i) => `${line}-${i}`).join('\n')
    const normalized = normalizePrBody(basePr(body))
    expect(normalized.clipped).toBe(true)
    expect([...normalized.summary].length).toBeLessThanOrEqual(2000)
    const withoutNotice = normalized.summary.endsWith(CLIP_NOTICE)
      ? normalized.summary.slice(0, -CLIP_NOTICE.length)
      : normalized.summary
    expect(body.startsWith(withoutNotice)).toBe(true)
    expect(withoutNotice.endsWith('\n')).toBe(false)
  })

  it('the clip notice itself counts toward the 2000-codepoint budget — total never exceeds it', () => {
    const body = `${'y'.repeat(1999)}\n${'z'.repeat(1999)}`
    const normalized = normalizePrBody(basePr(body))
    expect([...normalized.summary].length).toBeLessThanOrEqual(2000)
  })

  it('surrogate-pair-safe clipping — never splits a Unicode code point (e.g. an emoji) in half', () => {
    const emoji = String.fromCodePoint(0x1f600) // U+1F600, a surrogate pair: 2 UTF-16 units, 1 code point
    const words = Array.from({length: 600}, (_, i) => `word${i}${emoji}`)
    const body = words.join(' ')
    const normalized = normalizePrBody(basePr(body))
    expect(normalized.clipped).toBe(true)
    const codepoints = [...normalized.summary]
    expect(codepoints.join('')).toBe(normalized.summary)
    const hasLoneSurrogate = /[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]/.test(
      normalized.summary,
    )
    expect(hasLoneSurrogate).toBe(false)
  })

  it('a real secret/token straddling the budget boundary is never left as a partial fragment in the retained summary, and is correctly reported as redacted-source rather than silently "clean"', () => {
    const dummyToken = `ghp_${'6'.repeat(40)}` // 44 chars, no internal whitespace
    const padding = 'a '.repeat(990) // ~1980 codepoints of ordinary space-separated prose
    const body = `${padding}prefix-${dummyToken}-suffix`
    const normalized = normalizePrBody(basePr(body))
    for (let take = 8; take <= dummyToken.length; take += 4) {
      expect(normalized.summary).not.toContain(dummyToken.slice(0, take))
    }
    expect([...normalized.summary].length).toBeLessThanOrEqual(2000)
    expect(normalized.redactedSourceSecretRules).toEqual(['github-token'])
  })
})

describe('normalizePrBody: raw-vs-retained secret scan comparison (redacted-source vs hard-fail-worthy)', () => {
  it("reports NO redacted-source match when a raw secret sits in ordinary (retained) text — it remains in the summary for the caller's hard-fail scan to catch", () => {
    const dummyToken = `ghp_${'1'.repeat(40)}`
    const pr = basePr(`This PR adds the bootstrap script.\n\ntoken: ${dummyToken}`)
    const normalized = normalizePrBody(pr)
    expect(normalized.summary).toContain(dummyToken)
    expect(normalized.redactedSourceSecretRules).toEqual([])
  })

  it('titles/files still hard-fail via the caller scan: normalizePrBody itself never redacts a retained title/files value — it is left as-is for scanPayloadForSecrets to catch', () => {
    const dummyToken = `ghp_${'7'.repeat(40)}`
    const pr = basePr('ordinary body', {title: `feat: rotate ${dummyToken}`})
    const normalized = normalizePrBody(pr)
    expect(normalized.title).toContain(dummyToken)
  })

  it('reports a redacted-source match when a raw secret sits ONLY inside an omitted release-notes <details> block — never present in the retained summary', () => {
    const dummyCredentialedUrl = 'https://user:pass@example.com/registry'
    const body = [
      'This PR contains the following updates:',
      '',
      '| Package | Change |',
      '| --- | --- |',
      '| widget | 1.0.0 -> 1.1.0 |',
      '',
      '<details>',
      '<summary>widget (widget)</summary>',
      '',
      `pnpm no longer leaks credentials such as ${dummyCredentialedUrl} in its output.`,
      '',
      '</details>',
    ].join('\n')
    const normalized = normalizePrBody(basePr(body))
    expect(normalized.summary).not.toContain('user:pass')
    expect(normalized.redactedSourceSecretRules).toEqual(['credentialed-url'])
    expect(normalized.rawBodyHash).toMatch(/^[a-f0-9]{64}$/)
  })

  it('reports a redacted-source match when a raw secret sits ONLY inside a NESTED release-notes <details> block', () => {
    const dummyCredentialedUrl = 'https://user:pass@example.com/registry'
    const body = `INTRO\n\n<details>OUTER<details>See ${dummyCredentialedUrl} for details.</details>OUTER_TAIL</details>\n\nTRAILER`
    const normalized = normalizePrBody(basePr(body))
    expect(normalized.summary).not.toContain('user:pass')
    expect(normalized.redactedSourceSecretRules).toEqual(['credentialed-url'])
  })

  it('reports a redacted-source match when a raw secret sits ONLY inside a sponsors block', () => {
    const dummyCredentialedUrl = 'https://user:pass@example.com/registry'
    const body = [
      'Ordinary summary paragraph.',
      '',
      '<!-- sponsors -->',
      `See ${dummyCredentialedUrl} for our sponsor portal.`,
    ].join('\n')
    const normalized = normalizePrBody(basePr(body))
    expect(normalized.summary).not.toContain('user:pass')
    expect(normalized.redactedSourceSecretRules).toEqual(['credentialed-url'])
  })

  it('reports a redacted-source match when a raw secret sits ONLY in content clipped away by the description budget (present in raw, absent from the bounded retained summary)', () => {
    const dummyToken = `ghp_${'2'.repeat(40)}`
    // Space-separated padding (not a single unbroken run) so the budget clip lands via the
    // whitespace boundary, not the B1 title-fallback path — exercising the budget-clip branch of
    // the raw-vs-retained comparison specifically.
    const padding = Array.from({length: 500}, (_, i) => `word${i}`).join(' ')
    const body = `${padding} token: ${dummyToken}`
    const normalized = normalizePrBody(basePr(body))
    expect(normalized.clipped).toBe(true)
    expect(normalized.summary).not.toContain(dummyToken)
    expect(normalized.redactedSourceSecretRules).toEqual(['github-token'])
  })

  it('does not report a redacted-source match at all when the raw body has no secret-shaped content', () => {
    const normalized = normalizePrBody(basePr('This PR adds the bootstrap script.'))
    expect(normalized.redactedSourceSecretRules).toEqual([])
  })

  it('de-duplicates a rule name that would otherwise be reported once per occurrence', () => {
    const dummyToken1 = `ghp_${'3'.repeat(40)}`
    const dummyToken2 = `ghp_${'4'.repeat(40)}`
    const body = [
      '<details>',
      '<summary>x</summary>',
      `first: ${dummyToken1}`,
      `second: ${dummyToken2}`,
      '</details>',
    ].join('\n')
    const normalized = normalizePrBody(basePr(body))
    expect(normalized.redactedSourceSecretRules).toEqual(['github-token'])
  })

  it('never persists or exposes the raw body text itself when it was deterministically omitted — only a sha256 hash of the raw body is recorded', () => {
    const body =
      '<details><summary>x</summary>omitted release-notes prose with the word canary-marker-omitted</details>'
    const normalized = normalizePrBody(basePr(body))
    expect(normalized.rawBodyHash).toMatch(/^[a-f0-9]{64}$/)
    expect(JSON.stringify(normalized)).not.toContain('canary-marker-omitted')
  })

  it('a raw body with a DIFFERENT secret-containing text produces a different rawBodyHash (source traceability)', () => {
    const a = normalizePrBody(basePr('<details><summary>x</summary>one release note</details>'))
    const b = normalizePrBody(basePr('<details><summary>x</summary>a different release note</details>'))
    expect(a.rawBodyHash).not.toBe(b.rawBodyHash)
  })
})
