import {defineConfig} from 'tsdown'

export default defineConfig({
  entry: ['./src/index.ts'],
  outDir: 'dist',
  format: ['esm'],
  outExtensions: () => ({
    js: '.js',
    dts: '.d.ts',
  }),
  dts: {
    sourcemap: true,
  },
  sourcemap: true,
  clean: false, // Don't clean to preserve CSS files generated by Vite
  external: [
    // React ecosystem
    'react',
    'react-dom',
    'react-native',
    // Third-party UI dependencies
    '@radix-ui/react-form',
    '@radix-ui/react-label',
    '@radix-ui/react-primitive',
    '@radix-ui/react-select',
    'clsx',
    // CSS files - external since they're handled by Vite
    './styles.css',
    // Internal Sparkle packages
    '@sparkle/types',
    '@sparkle/utils',
    '@sparkle/theme',
    '@sparkle/config',
    '@sparkle/ui',
    '@sparkle/error-testing',
    '@sparkle/storybook',
  ],
  target: 'es2020',
})
